# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/deps/common"
      - "/deps/db"
      - "/deps/graph-parser"
      - "/deps/outliner"
      - "/deps/publishing"
      - "/libs"
      - "/resources"
      - "/scripts"
      - "/packages/amplify"
      - "/packages/tldraw"
      - "/packages/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"  
