[default]
extend-ignore-re = [
    "fnd\\.",      # Ignore 'fnd.' as a false positive
    "ANDed",       # Ignore 'ANDed' as a false positive
    "snD-IY-ifK"   # Ignore this identifier as a false positive
]

[default.extend-words]
# Technical words
edn = "edn"
datas = "datas"
juxt = "juxt"
referer = "referer" # This is a misspelling in the http spec so not much we can do

# False positives
collapsable = "collapsable" # This an ok alternative to collapsible
BA = "BA"
fo = "fo"
aks = "aks"
Mannor = "Mannor"
nd = "nd"
deleteable = "deleteable"
fom = "fom"
tne = "tne"
Damon = "Damon"
typ = "typ"
[files]
extend-exclude = ["resources/*", "src/resources/*", "scripts/resources/*", "src/test/fixtures/*", "src/test/migration/*.transit"]
