# This workflow tries to build iOS app
name: Build iOS

permissions:
  contents: read
on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '21'

jobs:
  build-ios:
    runs-on: macos-15
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}

      - name: Compile CLJS
        run: yarn install && yarn release-mobile

      - name: Prepare iOS build
        run: npx cap sync ios

      - name: List iOS build targets
        run: xcodebuild -list -workspace App.xcworkspace
        working-directory: ./ios/App

      - name: Build iOS App
        run: |
          xcodebuild -workspace App.xcworkspace -scheme Logseq -destination generic/platform=iOS build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        working-directory: ./ios/App
