# This is the main Android apk build workflow for both nightly and beta releases.
# This is also configured to run as a workflow_call.

name: Build Android

permissions:
  contents: read
on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '21'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}

      - name: Compile CLJS
        run: |
          yarn install
          yarn release-app
  
      - name: Prepare public Directory
        run: |
          cp -r static public/
          rm -rvf public/js/publishing
          rm -rvf public/js/*.js.map || true
          rm -rvf public/*.*
          rm -rvf public/ios
          rm -rvf android/app/src/main/assets/public || true
  
      - name: Sync public to Android Project
        run: npx cap sync android
    
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Android
        run: |
          ./gradlew clean
          ./gradlew zipApksForRelease
        working-directory: android
  
      - name: Rename Apk
        run: |
          mkdir builds
          mv android/app/build/outputs/apk/release/app-release-unsigned.apk ./builds/Logseq-android-unsigned.apk
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: logseq-android-builds
          path: builds