# workflow to check for typos
name: Check for Typos

permissions:
  contents: read
on:
  workflow_call:

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Check spelling with custom config file
        uses: crate-ci/typos@v1.35.7
        with:
          config: ./typos.toml