# workflow to coordinate the CI/CD process
name: CI/CD Workflow

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:

  check-typos:
    uses: ./.github/workflows/check-typos.yml

  lint:
    uses: ./.github/workflows/lint.yml

  compile:
    uses: ./.github/workflows/compile.yml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yml
    needs: [compile]

  test-db-graph:
    uses: ./.github/workflows/test-db-graph.yml
    needs: [compile]

  test-clojure-script:
    uses: ./.github/workflows/test-clojure-script.yml
    needs: [compile]

  test-deps:
    uses: ./.github/workflows/test-deps.yml
    needs: [compile]

  build-android:
    uses: ./.github/workflows/build-android.yml
    needs: [check-typos, lint, test-e2e, test-db-graph, test-clojure-script, test-deps]

  build-ios:
    uses: ./.github/workflows/build-ios.yml
    needs: [check-typos, lint, test-e2e, test-db-graph, test-clojure-script, test-deps]
  
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    needs: [check-typos, lint, test-e2e, test-db-graph, test-clojure-script, test-deps]

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    needs: [check-typos, lint, test-e2e, test-db-graph, test-clojure-script, test-deps]

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    needs: [check-typos, lint, test-e2e, test-db-graph, test-clojure-script, test-deps]
