# workflow to perform basic compilation of the codebase
name: Compile Workflow

permissions:
  contents: read
on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '21'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
    
      # Must set up Java before running some Clojure tools
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{env.JAVA_VERSION}}
    
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
    
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: ${{env.CLOJURE_VERSION}}
    
      - name: Compile CLJS
        run: |
          yarn install 
          gulp build
          yarn cljs:release-electron