# workflow to run lint checks
name: Lint Checks

permissions:
  contents: read
on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  JAVA_VERSION: '21'
  BABASHKA_VERSION: '1.0.168'

jobs:
  run-lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Must set up Java before running some Clojure tools
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{env.JAVA_VERSION}}

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: ${{env.CLOJURE_VERSION}}
          bb: ${{env.BABASHKA_VERSION}}

      - name: Run clj-kondo lint
        run: clojure -M:clj-kondo --parallel --lint src

      - name: Carve lint for unused vars
        run: bb lint:carve

      - name: Lint for vars that are too large
        run: bb lint:large-vars

      - name: Lint for namespaces that aren't documented
        run: bb lint:ns-docstrings

      - name: Lint invalid translation entries
        run: bb lang:validate-translations

      - name: Lint to keep worker independent of frontend
        run: bb lint:worker-and-frontend-separate

      - name: Lint to keep db and file graph code separate
        run: bb lint:db-and-file-graphs-separate