# workflow to run tests on deps
name: Test Deps

permissions:
  contents: read
on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '21'
  BABASHKA_VERSION: '1.0.168'

jobs:
  deps-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/db

      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/db

      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/db

  deps-graph-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch Clojure deps
        run: clojure -A:test -P
        working-directory: deps/graph-parser
  
      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/graph-parser
  
      - name: Run ClojureScript tests
        run: REPEATABLE_IDENTS=true clojure -M:test
        working-directory: deps/graph-parser
  
      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/graph-parser
  
      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/graph-parser

  deps-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      # Must set up Java before running some Clojure tools
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{env.JAVA_VERSION}}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{env.CLOJURE_VERSION}}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/common
  
      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/common
  
      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/common

      - name: Fetch Clojure deps
        run: clojure -A:test -P
        working-directory: deps/common

      - name: Run ClojureScript tests
        run: clojure -M:test
        working-directory: deps/common

  deps-outliner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Clojure needed for bb step
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/outliner

      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/outliner

      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/outliner

  deps-publishing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Clojure needed for bb step
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/publishing

      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/publishing

      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/publishing

  deps-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Clojure needed for bb step
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{ env.CLOJURE_VERSION }}
          bb: ${{ env.BABASHKA_VERSION }}

      - name: Fetch yarn deps
        run: yarn install --frozen-lockfile
        working-directory: deps/cli

      - name: Run nbb-logseq tests
        run: yarn test
        working-directory: deps/cli

      # In this job because it depends on an npm package
      - name: Load namespaces into nbb-logseq
        run: bb test:load-all-namespaces-with-nbb .
        working-directory: deps/cli