# workflow to test database graph creation and validation
name: DB Graph Tests

permissions:
  contents: read

on:
  workflow_call:

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '21'
  BABASHKA_VERSION: '1.0.168'

jobs:
  db-graph-test:
    name: DB Graph Tests
    strategy:
        matrix:
          operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v5

      # Must set up Java before running some Clojure tools
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{env.JAVA_VERSION}}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{env.CLOJURE_VERSION}}
          bb: ${{env.BABASHKA_VERSION}}

      - name: Fetch scripts yarn deps
        run: cd scripts && yarn install --frozen-lockfile

      - name: Create DB graph with properties
        run: cd scripts && yarn nbb-logseq src/logseq/tasks/db_graph/create_graph_with_properties.cljs ./properties-graph
  
      # TODO: Use a smaller, test-focused graph to test classes
      - name: Create DB graph with classes
        run: cd scripts && yarn nbb-logseq src/logseq/tasks/db_graph/create_graph_with_schema_org.cljs ./schema-graph
  
      - name: Fetch deps/db yarn deps
        run: cd deps/db && yarn install --frozen-lockfile
  
      - name: Validate created DB graphs
        run: cd deps/db && yarn nbb-logseq script/validate_db.cljs ../../scripts/properties-graph ../../scripts/schema-graph --closed-maps --group-errors
  
      - name: Export a created DB graph
        run: cd deps/db && yarn nbb-logseq script/export_graph.cljs ../../scripts/properties-graph -f properties.edn -T
  
      - name: Create graph from the export and diff the two graphs
        run: cd deps/db && yarn nbb-logseq -cp src:../outliner/src:script script/create_graph.cljs ./properties-graph2 properties.edn -iv && yarn nbb-logseq script/diff_graphs.cljs ../../scripts/properties-graph ./properties-graph2 -T 

